# Generated by Django 4.2.4 on 2024-01-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscriptionID', models.AutoField(primary_key=True, serialize=False)),
                ('subscription_type', models.CharField(choices=[('M', 'Monthly'), ('H', 'Half-Yearly'), ('Y', 'Yearly')], default=None, max_length=1)),
                ('start_date', models.DateField(default=None)),
                ('end_date', models.DateField(default=None)),
            ],
        ),
    ]
