# Generated by Django 4.2.4 on 2024-01-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('InstitutionID', models.AutoField(primary_key=True, serialize=False)),
                ('InstitutionName', models.CharField(max_length=255)),
                ('Address', models.CharField(blank=True, max_length=255, null=True)),
                ('ContactNumber', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
