# Generated by Django 4.2.4 on 2024-01-09 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Institution', '0001_initial'),
        ('Subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='Subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Institutions', to='Subscription.subscription'),
        ),
    ]
